language: python
rvm:
 - 3.9
 - os
 - time
 - ctypes
 - sys
 - zlib
 - getopt
 - logging
jobs:
  include:
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
install:
  - pip install -r requirements.txt
script:
  - python header.py
